### ISSUE TITLE
有使用说明吗？

### ISSUE THREAD

**Issue by seekcx** [stone-lyl/egg-sequelize-ts#1]
尝试了几种方案都无法运行。

**Comment by stone-lyl** [comment]
`/**
 * @desc OperateRecord表
 */
**import { Table, Column, Model, DataType, PrimaryKey, AutoIncrement } from 'sequelize-typescript';**
@Table({
    modelName: 'operate_record'
})
export class OperateRecord extends Model<OperateRecord> {
    @PrimaryKey
    @AutoIncrement
    @Column({
        type: DataType.INTEGER(11),
        comment: 'group member 关系 id'
    })
    id: number;

    @Column({
        comment: '用户姓名',
    })
    name: string;

    @Column({
        field: 'member_id'
    })
    memberId: number;

    @Column({
        comment: '用户操作描述',
    })
    desc: string;

    @Column({
        field: 'created_at'
    })
    createdAt: Date;

    @Column({
        field: 'updated_at'
    })
    updatedAt: Date;
};

export default () => OperateRecord;
`
通过`sequelize-typescript`导入所需的类型

**Comment by seekcx** [comment]
非常感谢
