### ISSUE TITLE
使用model 的 bulkCreate 方法，出错了

### ISSUE THREAD

**Issue by YSHIDM** [stone-lyl/egg-sequelize-ts#5]
环境：Windows10 wsl Ubuntu18.04
bulkCreate方法生成的 sql 变成了 insert into user (id,name) value (USER2020513001,'tom')
应该是： insert into user (id,name) value ('USER2020513001','tom')
id 的值缺少了引号
同环境下 create 方法是正确的

**Comment by stone-lyl** [comment]
你的id 在model中的定义是  `string` 还是 `number`?
